### ISSUE TITLE
Propose a table of contents of the documentation

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-plot-docs#12]
Currently we just tested the functionalities of the documentation but we should now write it ...

@wadjih-bencheikh18 please could you think about a table of contents of what should be the documentation like and propose it in this issue ?

**Comment by wadjih-bencheikh18** [comment]
Plot : 
- Heading
- legend ( example with callback, example with showHide )

Series:
- BarSeries
- FunctionSeries
- LineSeries
- RangeSeries
- ScatterSeries ( example with error bars , example with displaylines )

Axis :
- simple (log , time , linear)
- parallel

Annotations :
- Filled Annotations (Circle , Ellipse, DirectedEllipse, Rectangle ,Shape ,Polygone)
- No Filled Annotations (Line, Arrow, Text, Polyline )
- Group

Hooks :
- Basic (useStartMoveEnd , usePlotControllerAxes )
- Draw (useDrawRectangle , useDrawPath )
- Functionalities ( usePan , useAxisZoom, useRectangleZoom, useAxisWheelZoom )

**Comment by stropitek** [comment]
My suggestions:
Annotations:
  - Text
  - Filled shapes
  - Other shapes

Hooks:
"Functionalities" -> "Fonctional"

I think talking about the legend makes more sense at the end rather than at the beginning. You never start a plot by thinking about the legend. My suggestion for the order: Series, Axis, Annotations, Plot, Hooks

**Comment by wadjih-bencheikh18** [comment]
> Getting started

yeah we need this section

> I think talking about the legend makes more sense at the end rather than at the beginning. You never start a plot by thinking about the legend. My suggestion for the order: Series, Axis, Annotations, Plot, Hooks

i agree with this order

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 Please start to refactor the documentation and add text / examples.

**Comment by wadjih-bencheikh18** [comment]
@lpatiny could you please help
i got this error
`Module not found: Error: Can't resolve '....srccomponentsCodeSandboxer.tsx'`

**Comment by stropitek** [comment]
Hello @wadjih-bencheikh18 

I did the part with code sandbox. Can you push your code to a branch so I can have a look?

**Comment by wadjih-bencheikh18** [comment]
> Hello @wadjih-bencheikh18 
> 
> I did the part with code sandbox. Can you push your code to a branch so I can have a look?


I have this error without adding any changes

`npm i && npm start`

**Comment by stropitek** [comment]
Can you try `npm ci`? Are you on windows?

**Comment by stropitek** [comment]
Should be fixed on main

**Comment by wadjih-bencheikh18** [comment]
> Can you try `npm ci`? Are you on windows?

yes i'm on windows
i'm getting same erros 
![image](https://user-images.githubusercontent.com/56769876/159056185-b32572a0-ae24-4ff4-8b9f-be9501ccc922.png)
