### ISSUE TITLE
Adapt CodeSandbox link to React 18

### ISSUE THREAD

**Issue by targos** [zakodium-oss/react-plot-docs#19]
It works, but prints a warning:

![image](https://user-images.githubusercontent.com/2352663/165938662-7551095a-1578-4cff-ab79-1d88fbe353e3.png)

**Comment by stropitek** [comment]
Pinned react version to 17 in https://github.com/zakodium-oss/react-plot-docs/commit/a8a7d9f52b29e60cdb0483823d2b075dfba6003f
