### ISSUE TITLE
Update code-sandbox dependencies

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-plot-docs#23]
@stropitek could you tell us how to update code sandbox dependencies ?

ml-spectra-processing should be updated to 11.6.0

**Comment by stropitek** [comment]
I'm not sure exactly what you mean but I think we need to read the imports of the demo to know which dependencies are needed and then read the `package.json` to get the version to be added to the `package.json` which will be sent to code sandbox

**Comment by lpatiny** [comment]
Yes it was my mistake. The documentation is build using the package-lock.json and on code sandbox it is the last version that is being used. In this specific case I renamed a property 'Q1' to 'q1' without making a breaking change in ml-spectra-processing and there was an issue.

Updating ml-spectra-processing in this package solved the problem.
