### ISSUE TITLE
Question: drawRectangle hook

### ISSUE THREAD

**Issue by santimirandarp** [zakodium-oss/react-plot-docs#31]
Hi, I am reading through the docs for learning and fixing some typos. They are great.

For the `useDrawRectangle` if you draw one by clicking and dragging it disappears unless you hold (I guess this is the purpose). However, if we press **Alt** and mouse off the chart it stays till you click somewhere else. Same for `useDrawPath`.

Are both of these (w or w/o Alt) what the hook provide or which one?

In the first case maybe that should be documented?

**Comment by stropitek** [comment]
It sounds like a bug to me. Support for modifier keys was added for hooks like `usePan` but I think in this case using `alt` should have no effect

**Comment by santimirandarp** [comment]
I see, thanks. I'll add an issue tom. and close this one then.
